name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: issue-93-gh-actions
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run prepare
      - run: npm run docs
      - name: Publish Release ${{ github.event.release.name }}
        run: |
          PKG_VERSION=$(npm version from-git)
          npm publish --tag=latest
          PUBLISH_AS_IS=$?
          if [[ $PUBLISH_AS_IS -eq 0 ]]; then
            echo "Release $PKG_VERSION published"
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git add README.md package.json package-lock.json
            git status
            git commit -m":package: [skip ci] Release \`$PKG_VERSION\` by :robot:

          Co-authored-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          "
            git log -n 2
            exit 0
          else
            echo "Error exit code $PUBLISH_AS_IS" && exit $PUBLISH_AS_IS
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Version Update
        uses: ad-m/github-push-action@master
        with:
          branch: issue-93-gh-actions
          github_token: ${{ secrets.GITHUB_TOKEN }}
